# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dcmMvDialog.ui'
#
# Created by: PySide2 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_DcmMvDialogUI(object):
    def setupUi(self, DcmMvDialogUI):
        DcmMvDialogUI.setObjectName("DcmMvDialogUI")
        DcmMvDialogUI.resize(676, 613)
        self.verticalLayout = QtWidgets.QVBoxLayout(DcmMvDialogUI)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(DcmMvDialogUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.source_location_text = QtWidgets.QLineEdit(DcmMvDialogUI)
        self.source_location_text.setEnabled(False)
        self.source_location_text.setObjectName("source_location_text")
        self.horizontalLayout.addWidget(self.source_location_text)
        self.source_choose_button = QtWidgets.QPushButton(DcmMvDialogUI)
        self.source_choose_button.setObjectName("source_choose_button")
        self.horizontalLayout.addWidget(self.source_choose_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(DcmMvDialogUI)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.destination_location_text = QtWidgets.QLineEdit(DcmMvDialogUI)
        self.destination_location_text.setEnabled(False)
        self.destination_location_text.setObjectName("destination_location_text")
        self.horizontalLayout_2.addWidget(self.destination_location_text)
        self.destination_choose_button = QtWidgets.QPushButton(DcmMvDialogUI)
        self.destination_choose_button.setObjectName("destination_choose_button")
        self.horizontalLayout_2.addWidget(self.destination_choose_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.move_radio = QtWidgets.QRadioButton(DcmMvDialogUI)
        self.move_radio.setChecked(True)
        self.move_radio.setObjectName("move_radio")
        self.horizontalLayout_4.addWidget(self.move_radio)
        self.copy_radio = QtWidgets.QRadioButton(DcmMvDialogUI)
        self.copy_radio.setObjectName("copy_radio")
        self.horizontalLayout_4.addWidget(self.copy_radio)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(DcmMvDialogUI)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_5 = QtWidgets.QLabel(DcmMvDialogUI)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(DcmMvDialogUI)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.pattern_text = QtWidgets.QLineEdit(DcmMvDialogUI)
        self.pattern_text.setObjectName("pattern_text")
        self.horizontalLayout_3.addWidget(self.pattern_text)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.progressBar = QtWidgets.QProgressBar(DcmMvDialogUI)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.move_button = QtWidgets.QPushButton(DcmMvDialogUI)
        self.move_button.setEnabled(False)
        self.move_button.setObjectName("move_button")
        self.verticalLayout.addWidget(self.move_button)

        self.retranslateUi(DcmMvDialogUI)
        QtCore.QMetaObject.connectSlotsByName(DcmMvDialogUI)

    def retranslateUi(self, DcmMvDialogUI):
        _translate = QtCore.QCoreApplication.translate
        DcmMvDialogUI.setWindowTitle(_translate("DcmMvDialogUI", "Form"))
        self.label.setText(_translate("DcmMvDialogUI", "Source:"))
        self.source_choose_button.setText(_translate("DcmMvDialogUI", "Choose..."))
        self.label_2.setText(_translate("DcmMvDialogUI", "Destination:"))
        self.destination_choose_button.setText(_translate("DcmMvDialogUI", "Choose..."))
        self.move_radio.setText(_translate("DcmMvDialogUI", "Move files"))
        self.copy_radio.setText(_translate("DcmMvDialogUI", "Copy files"))
        self.label_3.setText(_translate("DcmMvDialogUI", "<html><head/><body><p>Example placeholders (any dicom tag name can be used):</p></body></html>"))
        self.label_4.setText(_translate("DcmMvDialogUI", "Pattern:"))
        self.pattern_text.setText(_translate("DcmMvDialogUI", "%PatientName%/%StudyDate%/%SeriesNumber%_%SeriesName%/"))
        self.move_button.setText(_translate("DcmMvDialogUI", "Move"))
